[workspace]
members = [
  "crates/hydebar-proto",
  "crates/hydebar-core",
  "crates/hydebar-gui",
  "crates/hydebar-app",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"

[workspace.dependencies]
iced = { git = "https://github.com/pop-os/iced", features = [
  "tokio",
  "advanced",
  "wgpu",
  "winit",
  "wayland",
  "cctk",
  "image",
  "lazy",
  "svg",
  "canvas",
] }
chrono = "0.4"
hyprland = "0.4.0-beta.3"
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.39"
tokio = { version = "1", features = ["full", "test-util"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
libpulse-binding = { version = "2", features = ["pa_v15"] }
log = { version = "0.4", features = ["serde"] }
flexi_logger = "0.31"
pipewire = "0.10"
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "unstable"] }
itertools = "0.15"
hex_color = { version = "3", features = ["serde"] }
udev = { version = "0.9", features = ["send", "sync"] }
toml = "1"
freedesktop-icons = "0.4"
linicon-theme = "1"
serde_json = "1"
regex = "1"
serde_with = "3"
tokio-stream = "0.1"
uuid = { version = "1", features = ["v4"] }
clap = { version = "4", features = ["derive"] }
shellexpand = { version = "3", features = ["path"] }
inotify = "0.11"
masterror = "0.29"
futures = "0.3"
dirs = "6"
reqwest = { version = "0.13", features = ["json"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[patch."https://github.com/pop-os/iced"]
iced = { path = "./iced-patch" }
