// TODO: Fix broken tests
#[cfg(all(test, feature = "enable-broken-tests"))]
mod tests {
    use iced::{Background, Theme};

    use super::*;

    fn color(background: Option<Background>) -> Color {
        match background.expect("background should be set") {
            Background::Color(color) => color,
            other => panic!("unexpected background: {other:?}")
        }
    }

    #[test]
    fn module_button_style_respects_transparency() {
        let theme = Theme::default();
        let style_fn = module_button_style(AppearanceStyle::Islands, 0.5, true);

        let active = style_fn(&theme, Status::Active);
        assert!(active.background.is_none());

        let hover_fn = module_button_style(AppearanceStyle::Islands, 0.5, false);
        let hovered = hover_fn(&theme, Status::Hovered);
        assert_eq!(
            color(hovered.background),
            theme
                .extended_palette()
                .background
                .weak
                .color
                .scale_alpha(0.5)
        );
    }

    #[test]
    fn ghost_button_style_sets_hover_background() {
        let theme = Theme::default();
        let style_fn = ghost_button_style(0.4);

        let hovered = style_fn(&theme, Status::Hovered);
        assert_eq!(
            color(hovered.background),
            theme
                .extended_palette()
                .background
                .weak
                .color
                .scale_alpha(0.4)
        );
    }

    #[test]
    fn outline_button_style_has_border() {
        let theme = Theme::default();
        let style_fn = outline_button_style(0.2);
        let active = style_fn(&theme, Status::Active);

        assert_eq!(active.border.width, 2.0);
        assert_eq!(active.border.radius, 32.0.into());
        assert_eq!(
            active.border.color,
            theme.extended_palette().background.weak.color
        );
    }

    #[test]
    fn confirm_button_style_hoveres_to_strong_background() {
        let theme = Theme::default();
        let style_fn = confirm_button_style(0.8);

        let hovered = style_fn(&theme, Status::Hovered);
        assert_eq!(
            color(hovered.background),
            theme
                .extended_palette()
                .background
                .strong
                .color
                .scale_alpha(0.8)
        );
    }

    #[test]
    fn settings_button_style_hoveres_to_strong_background() {
        let theme = Theme::default();
        let style_fn = settings_button_style(0.6);

        let hovered = style_fn(&theme, Status::Hovered);
        assert_eq!(
            color(hovered.background),
            theme
                .extended_palette()
                .background
                .strong
                .color
                .scale_alpha(0.6)
        );
    }

    #[test]
    fn workspace_button_style_handles_empty_state() {
        let theme = Theme::default();
        let style_fn = workspace_button_style(true, None);

        let active = style_fn(&theme, Status::Active);
        assert_eq!(
            color(active.background),
            theme.extended_palette().background.weak.color
        );
        assert_eq!(active.border.width, 1.0);
    }

    #[test]
    fn workspace_button_style_uses_custom_colors() {
        let theme = Theme::default();
        let custom_color = AppearanceColor::Complete {
            base:   hex_color::HexColor::rgb(200, 100, 50),
            strong: Some(hex_color::HexColor::rgb(210, 110, 60)),
            weak:   Some(hex_color::HexColor::rgb(190, 90, 40)),
            text:   Some(hex_color::HexColor::rgb(10, 20, 30))
        };
        let style_fn = workspace_button_style(false, Some(Some(custom_color)));

        let hovered = style_fn(&theme, Status::Hovered);
        assert_eq!(hovered.border.radius, 16.0.into());
        assert_eq!(color(hovered.background).a, 1.0);
        // Text color is generated by palette::Primary::generate, not used
        // directly
    }

    #[test]
    fn quick_settings_button_style_switches_palette() {
        let theme = Theme::default();
        let inactive = quick_settings_button_style(false, 0.5);
        let active = quick_settings_button_style(true, 0.5);

        let inactive_hover = inactive(&theme, Status::Hovered);
        let active_hover = active(&theme, Status::Hovered);

        assert_eq!(
            color(inactive_hover.background),
            theme
                .extended_palette()
                .background
                .strong
                .color
                .scale_alpha(0.5)
        );
        assert_eq!(
            color(active_hover.background),
            theme.extended_palette().primary.weak.color.scale_alpha(0.5)
        );
    }

    #[test]
    fn quick_settings_submenu_button_style_hover_changes_text_color() {
        let theme = Theme::default();
        let style_fn = quick_settings_submenu_button_style(false, 0.4);

        let hovered = style_fn(&theme, Status::Hovered);
        assert_eq!(hovered.text_color, theme.palette().text);
        assert_eq!(
            color(hovered.background),
            theme
                .extended_palette()
                .background
                .weak
                .color
                .scale_alpha(0.4)
        );
    }
}
