//! Stylesheet fixtures and assertions shared by the reader tests.

use std::{
    fs,
    path::{Path, PathBuf}
};

pub(super) const THEME_CSS: &str = r"
/* generated by HyDE */
@define-color bar-bg rgba(27,29,28,0.01);
@define-color main-bg   rgba( 27 , 29 , 28 , 0.8 ) ;
@define-color main-fg #AAF0CD;
@define-color wb-act-bg rgb(195,172,118);
@define-color wb-act-fg rgba(255,240,204,1);
@define-color wb-hvr-bg #7d6c4b66;
@define-color wb-hvr-fg rgba(240,204,170,0.8);
@define-color unknown-key rgba(1,2,3,1);
@define-color broken-key not-a-color;
";

pub(super) const GLOBAL_CSS: &str = r#"
/*
 Dynamic Style Configuration
*/

* {
    border-radius: 0em;
    font-family: "JetBrainsMono Nerd Font","JetBrainsMono Nerd Font";
    font-size: 10px;
}
"#;

pub(super) const BORDER_RADIUS_CSS: &str = r"
/* ? Leaf shape */
window#waybar.top #leaf,
window#waybar.top #leaf button {
    border-radius: 9pt 0 9pt 0;
}

/* ? half pill with the flat surface pointing upwards */
window#waybar.top #pill-up,
window#waybar.top #pill-up button {
    border-radius: 7pt 7pt 0 0;
}

window#waybar.top #pill-in tooltip {
    border-radius: 0 0 5pt 5pt;
}

/* ? Full Pill shape */
window#waybar.bottom #pill menuitem,
window#waybar.top #pill,
window#waybar.top #pill button {
    border-radius: 3pt 3pt 3pt 3pt;
}

tooltip {
    border-radius: 11pt;
}
";

/// Writes the three `HyDE` stylesheets into a temporary configuration root.
pub(super) fn write_fixture(root: &Path) -> PathBuf {
    let waybar = root.join("waybar");
    let includes = waybar.join("includes");
    fs::create_dir_all(&includes).expect("create fixture directories");

    fs::write(waybar.join("theme.css"), THEME_CSS).expect("write theme.css");
    fs::write(includes.join("global.css"), GLOBAL_CSS).expect("write global.css");
    fs::write(includes.join("border-radius.css"), BORDER_RADIUS_CSS)
        .expect("write border-radius.css");

    waybar
}

pub(super) fn assert_close(actual: f32, expected: f32) {
    assert!(
        (actual - expected).abs() < 1e-4,
        "expected {expected}, got {actual}"
    );
}
