//! The glyphs compiled into the binary, one per icon.

use super::Icons;

impl Icons {
    /// Glyph compiled into the binary, used when no override applies.
    #[must_use]
    #[expect(
        clippy::match_same_arms,
        reason = "each icon names its own glyph even when glyphs coincide"
    )]
    pub const fn default_glyph(self) -> &'static str {
        match self {
            Self::None => "",
            Self::AppLauncher => "󱗼",
            Self::Clipboard => "󰅌",
            Self::Refresh => "󰑐",
            Self::Trash => "󰆴",
            Self::Download => "󰇚",
            Self::ViewGrid => "󰕰",
            Self::ViewList => "󰕳",
            Self::NoUpdatesAvailable => "󰗠",
            Self::UpdatesAvailable => "󰳛",
            Self::MenuClosed => "",
            Self::MenuOpen => "",
            Self::Cpu => "󰔂",
            Self::Gpu => "󰢮",
            Self::IntegratedGpu => "󰘚",
            Self::Accelerator => "󰧑",
            Self::Mem => "",
            Self::Temp => "󰔏",
            Self::Speaker0 => "󰸈",
            Self::Speaker1 => "󰕿",
            Self::Speaker2 => "󰖀",
            Self::Speaker3 => "󰕾",
            Self::Headphones0 => "󰟎",
            Self::Headphones1 => "󰋋",
            Self::Headset => "󰋎",
            Self::Mic0 => "󰍭",
            Self::Mic1 => "󰍬",
            Self::ScreenShare => "󱒃",
            Self::MonitorSpeaker => "󰽟",
            Self::Battery0 => "󰂃",
            Self::Battery1 => "󰁼",
            Self::Battery2 => "󰁾",
            Self::Battery3 => "󰂀",
            Self::Battery4 => "󰁹",
            Self::BatteryCharging => "󰂄",
            Self::Wifi0 => "󰤭",
            Self::Wifi1 => "󰤯",
            Self::Wifi2 => "󰤟",
            Self::Wifi3 => "󰤢",
            Self::Wifi4 => "󰤥",
            Self::Wifi5 => "󰤨",
            Self::WifiLock1 => "󰤬",
            Self::WifiLock2 => "󰤡",
            Self::WifiLock3 => "󰤤",
            Self::WifiLock4 => "󰤧",
            Self::WifiLock5 => "󰤪",
            Self::Ethernet => "󰈀",
            Self::Vpn => "󰖂",
            Self::Bluetooth => "󰂯",
            Self::PowerSaver => "󰾆",
            Self::Balanced => "󰾅",
            Self::Performance => "󰓅",
            Self::EyeOpened => "󰈈",
            Self::EyeClosed => "󰈉",
            Self::Lock => "󰌾",
            Self::Power => "󰐥",
            Self::Reboot => "󰑐",
            Self::Suspend => "󰤄",
            Self::Logout => "󰗽",
            Self::LeftArrow => "󰁍",
            Self::RightArrow => "󰁔",
            Self::LeftChevron => "󰅁",
            Self::RightChevron => "󰅂",
            Self::Brightness => "󰃠",
            Self::Point => "",
            Self::AreaSelect => "\u{f0a6c}",
            Self::Bell => "\u{f009a}",
            Self::Camera => "\u{f0100}",
            Self::Fullscreen => "\u{f0293}",
            Self::Record => "\u{f044a}",
            Self::Stop => "\u{f04db}",
            Self::WindowCapture => "\u{f05af}",
            Self::Close => "󰅖",
            Self::Airplane => "󰀝",
            Self::Webcam => "",
            Self::SkipPrevious => "󰒮",
            Self::Play => "󰐊",
            Self::Pause => "󰏤",
            Self::SkipNext => "󰒭",
            Self::MusicNote => "󰎇",
            Self::Drive => "󰋊",
            Self::IpAddress => "󰩠",
            Self::DownloadSpeed => "󰛴",
            Self::UploadSpeed => "󰛶",
            Self::Copy => "󰆏",
            Self::IdleInhibitorActive => "\u{f0176}",
            Self::IdleInhibitorInactive => "\u{f06ca}",
            Self::Settings => "\u{f0493}",
            Self::Themes => "\u{f00e1}",
            Self::Wallpaper => "\u{f0b7c}",
            Self::BarLayout => "\u{f1985}",
            Self::KeybindHint => "\u{f030c}",
            Self::NightLight => "\u{f0748}",
            Self::GameMode => "\u{f0eb5}",
            Self::Weather => "\u{f0590}",
            Self::Authored => "\u{f04ce}"
        }
    }
}
