//! The configuration keys the icons answer to.

use super::Icons;

impl Icons {
    /// Key used to address the icon inside the `[icons]` configuration table.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::AppLauncher => "app_launcher",
            Self::Clipboard => "clipboard",
            Self::Refresh => "refresh",
            Self::Trash => "trash",
            Self::Download => "download",
            Self::ViewGrid => "view_grid",
            Self::ViewList => "view_list",
            Self::NoUpdatesAvailable => "no_updates_available",
            Self::UpdatesAvailable => "updates_available",
            Self::MenuClosed => "menu_closed",
            Self::MenuOpen => "menu_open",
            Self::Cpu => "cpu",
            Self::Gpu => "gpu",
            Self::IntegratedGpu => "integrated_gpu",
            Self::Accelerator => "accelerator",
            Self::Mem => "mem",
            Self::Temp => "temp",
            Self::Speaker0 => "speaker0",
            Self::Speaker1 => "speaker1",
            Self::Speaker2 => "speaker2",
            Self::Speaker3 => "speaker3",
            Self::Headphones0 => "headphones0",
            Self::Headphones1 => "headphones1",
            Self::Headset => "headset",
            Self::Mic0 => "mic0",
            Self::Mic1 => "mic1",
            Self::MonitorSpeaker => "monitor_speaker",
            Self::ScreenShare => "screen_share",
            Self::Battery0 => "battery0",
            Self::Battery1 => "battery1",
            Self::Battery2 => "battery2",
            Self::Battery3 => "battery3",
            Self::Battery4 => "battery4",
            Self::BatteryCharging => "battery_charging",
            Self::Wifi0 => "wifi0",
            Self::Wifi1 => "wifi1",
            Self::Wifi2 => "wifi2",
            Self::Wifi3 => "wifi3",
            Self::Wifi4 => "wifi4",
            Self::Wifi5 => "wifi5",
            Self::WifiLock1 => "wifi_lock1",
            Self::WifiLock2 => "wifi_lock2",
            Self::WifiLock3 => "wifi_lock3",
            Self::WifiLock4 => "wifi_lock4",
            Self::WifiLock5 => "wifi_lock5",
            Self::Ethernet => "ethernet",
            Self::Vpn => "vpn",
            Self::Bluetooth => "bluetooth",
            Self::PowerSaver => "power_saver",
            Self::Balanced => "balanced",
            Self::Performance => "performance",
            Self::EyeOpened => "eye_opened",
            Self::EyeClosed => "eye_closed",
            Self::Lock => "lock",
            Self::Power => "power",
            Self::Reboot => "reboot",
            Self::Suspend => "suspend",
            Self::Logout => "logout",
            Self::LeftArrow => "left_arrow",
            Self::RightArrow => "right_arrow",
            Self::LeftChevron => "left_chevron",
            Self::RightChevron => "right_chevron",
            Self::Brightness => "brightness",
            Self::Point => "point",
            Self::AreaSelect => "area_select",
            Self::Bell => "bell",
            Self::Camera => "camera",
            Self::Fullscreen => "fullscreen",
            Self::Record => "record",
            Self::Stop => "stop",
            Self::WindowCapture => "window_capture",
            Self::Close => "close",
            Self::Airplane => "airplane",
            Self::Webcam => "webcam",
            Self::SkipPrevious => "skip_previous",
            Self::Play => "play",
            Self::Pause => "pause",
            Self::SkipNext => "skip_next",
            Self::MusicNote => "music_note",
            Self::Drive => "drive",
            Self::IpAddress => "ip_address",
            Self::DownloadSpeed => "download_speed",
            Self::UploadSpeed => "upload_speed",
            Self::Copy => "copy",
            Self::IdleInhibitorActive => "idle_inhibitor_active",
            Self::IdleInhibitorInactive => "idle_inhibitor_inactive",
            Self::Settings => "settings",
            Self::Themes => "themes",
            Self::Wallpaper => "wallpaper",
            Self::BarLayout => "bar_layout",
            Self::KeybindHint => "keybind_hint",
            Self::NightLight => "night_light",
            Self::GameMode => "game_mode",
            Self::Weather => "weather",
            Self::Authored => "authored"
        }
    }

    /// Resolves a configuration key back to the icon it addresses.
    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|icon| icon.name() == name)
    }
}
