[package]
name = "hydebar-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
hydebar-core = { path = "../core" }
hydebar-proto = { path = "../proto" }
iced.workspace = true
iced_core.workspace = true
iced_futures.workspace = true
flexi_logger.workspace = true
log.workspace = true
tokio.workspace = true

[dev-dependencies]
# Enable test utilities from hydebar-core
hydebar-core = { path = "../core", features = ["test-utils"] }
iced_test = "0.14"

[lints]
workspace = true
