//! Reader for the theme generated by the [HyDE Project](https://github.com/HyDE-Project).
//!
//! HyDE renders its active theme into a handful of Waybar stylesheets. This
//! module reads those files and exposes the values the bar cares about
//! (colors, font and corner radius) so the appearance can follow the desktop
//! theme instead of hardcoded constants.
//!
//! The reader is intentionally forgiving: every file is optional, unknown
//! declarations are ignored and a value that cannot be understood simply stays
//! [`None`].
//!
//! The color type and its CSS notations live in [`color`], the stylesheet
//! tokenizer in [`css`], length conversion in [`length`], the per-file
//! extraction rules in [`extract`] and the snapshot with its entry points in
//! [`theme`].

mod color;
mod css;
mod extract;
mod length;
mod theme;

#[cfg(test)]
mod fixtures;

pub use color::Rgba;
pub use theme::{HydeTheme, load, load_from};
