//! Reader for the theme generated by the [HyDE Project](https://github.com/HyDE-Project).
//!
//! HyDE renders its active theme into a handful of Waybar stylesheets. This
//! module reads those files and exposes the values the bar cares about
//! (colors, font and corner radius) so the appearance can follow the desktop
//! theme instead of hardcoded constants.
//!
//! The reader is intentionally forgiving: every file is optional, unknown
//! declarations are ignored and a value that cannot be understood simply stays
//! [`None`].

use std::{
    fs,
    path::{Path, PathBuf}
};

/// Conversion factor between CSS points and CSS pixels.
const PX_PER_PT: f32 = 96.0 / 72.0;

/// Fallback font size used to resolve `em` lengths when the stylesheet does not
/// declare one.
const DEFAULT_EM_PX: f32 = 16.0;

/// Straight (non premultiplied) color with an alpha channel in `0.0..=1.0`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Rgba {
    /// Red channel.
    pub r: u8,
    /// Green channel.
    pub g: u8,
    /// Blue channel.
    pub b: u8,
    /// Alpha channel, where `1.0` is fully opaque.
    pub a: f32
}

impl Rgba {
    /// Builds an opaque color from its channels.
    #[must_use]
    pub const fn rgb(r: u8, g: u8, b: u8) -> Self {
        Self {
            r,
            g,
            b,
            a: 1.0
        }
    }

    /// Builds a color from its channels and an explicit alpha.
    #[must_use]
    pub const fn rgba(r: u8, g: u8, b: u8, a: f32) -> Self {
        Self {
            r,
            g,
            b,
            a
        }
    }
}

/// Snapshot of the HyDE theme as read from the Waybar stylesheets.
///
/// Every field is independent: a missing or malformed source leaves only the
/// affected fields as [`None`].
#[derive(Debug, Clone, Default, PartialEq)]
pub struct HydeTheme {
    /// Background of the bar surface (`bar-bg`).
    pub bar_background:    Option<Rgba>,
    /// Background of an individual module (`main-bg`).
    pub module_background: Option<Rgba>,
    /// Default foreground color (`main-fg`).
    pub text:              Option<Rgba>,
    /// Background of an active module (`wb-act-bg`).
    pub active_background: Option<Rgba>,
    /// Foreground of an active module (`wb-act-fg`).
    pub active_text:       Option<Rgba>,
    /// Background of a hovered module (`wb-hvr-bg`).
    pub hover_background:  Option<Rgba>,
    /// Foreground of a hovered module (`wb-hvr-fg`).
    pub hover_text:        Option<Rgba>,
    /// Font family declared for every widget.
    pub font_family:       Option<String>,
    /// Font size in CSS pixels.
    pub font_size_px:      Option<f32>,
    /// Corner radius of a full pill, in CSS pixels.
    pub radius_px:         Option<f32>
}

/// Reads the HyDE theme from the Waybar stylesheets under `config_dir`.
///
/// `config_dir` is the XDG configuration root (typically `~/.config`); the
/// Waybar files are looked up under `<config_dir>/waybar`.
///
/// This function never fails. Unreadable files, unknown keys and unparsable
/// values are skipped.
#[must_use]
pub fn load_from(config_dir: &Path) -> HydeTheme {
    let waybar = config_dir.join("waybar");

    let mut theme = HydeTheme::default();

    if let Some(source) = read_stylesheet(&waybar.join("theme.css")) {
        apply_colors(&mut theme, &source);
    }

    if let Some(source) = read_stylesheet(&waybar.join("includes").join("global.css")) {
        apply_global(&mut theme, &source);
    }

    if let Some(source) = read_stylesheet(&waybar.join("includes").join("border-radius.css")) {
        theme.radius_px = parse_pill_radius(&source, theme.font_size_px);
    }

    theme
}

/// Reads the HyDE theme from the user's configuration directory.
///
/// The directory is resolved from `XDG_CONFIG_HOME`, falling back to
/// `$HOME/.config`. When neither variable is set the returned theme is empty.
#[must_use]
pub fn load() -> HydeTheme {
    match config_dir() {
        Some(dir) => load_from(&dir),
        None => HydeTheme::default()
    }
}

/// Resolves the XDG configuration directory.
fn config_dir() -> Option<PathBuf> {
    if let Some(dir) = non_empty_var("XDG_CONFIG_HOME") {
        return Some(PathBuf::from(dir));
    }

    non_empty_var("HOME").map(|home| PathBuf::from(home).join(".config"))
}

/// Returns an environment variable only when it holds a non empty value.
fn non_empty_var(key: &str) -> Option<String> {
    std::env::var(key).ok().filter(|value| !value.is_empty())
}

/// Reads a stylesheet and removes its comments, returning [`None`] when the
/// file is missing or unreadable.
fn read_stylesheet(path: &Path) -> Option<String> {
    fs::read_to_string(path)
        .ok()
        .map(|raw| strip_comments(&raw))
}

/// Removes `/* ... */` comments from a stylesheet.
///
/// An unterminated comment swallows the rest of the input, which mirrors the
/// behaviour of a CSS parser.
fn strip_comments(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    let mut rest = source;

    while let Some(start) = rest.find("/*") {
        out.push_str(&rest[..start]);
        out.push(' ');

        match rest[start + 2..].find("*/") {
            Some(end) => rest = &rest[start + 2 + end + 2..],
            None => return out
        }
    }

    out.push_str(rest);
    out
}

/// Fills the color fields from a `theme.css` source.
fn apply_colors(theme: &mut HydeTheme, source: &str) {
    for (name, value) in define_colors(source) {
        let Some(color) = parse_color(&value) else {
            continue;
        };

        match name.as_str() {
            "bar-bg" => theme.bar_background = Some(color),
            "main-bg" => theme.module_background = Some(color),
            "main-fg" => theme.text = Some(color),
            "wb-act-bg" => theme.active_background = Some(color),
            "wb-act-fg" => theme.active_text = Some(color),
            "wb-hvr-bg" => theme.hover_background = Some(color),
            "wb-hvr-fg" => theme.hover_text = Some(color),
            _ => {}
        }
    }
}

/// Extracts every `@define-color <name> <value>;` pair from a stylesheet.
fn define_colors(source: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut rest = source;

    while let Some(start) = rest.find("@define-color") {
        let tail = &rest[start + "@define-color".len()..];
        let (declaration, remainder) = match tail.find(';') {
            Some(end) => (&tail[..end], &tail[end + 1..]),
            None => (tail, "")
        };
        rest = remainder;

        let declaration = declaration.trim();
        let Some(split) = declaration.find(char::is_whitespace) else {
            continue;
        };

        let name = declaration[..split].trim();
        let value = declaration[split..].trim();

        if !name.is_empty() && !value.is_empty() {
            out.push((name.to_owned(), value.to_owned()));
        }
    }

    out
}

/// Fills the font fields from a `global.css` source.
fn apply_global(theme: &mut HydeTheme, source: &str) {
    let body = universal_block(source).unwrap_or_else(|| source.to_owned());

    for (property, value) in declarations(&body) {
        match property.as_str() {
            "font-family" => {
                if theme.font_family.is_none() {
                    theme.font_family = parse_font_family(&value);
                }
            }
            "font-size" => {
                if theme.font_size_px.is_none() {
                    theme.font_size_px = parse_length(&value, None);
                }
            }
            _ => {}
        }
    }
}

/// Returns the body of the `*` rule, if the stylesheet declares one.
fn universal_block(source: &str) -> Option<String> {
    blocks(source)
        .into_iter()
        .find(|(selector, _)| selector.trim() == "*")
        .map(|(_, body)| body)
}

/// Splits a stylesheet into `(selector, body)` pairs.
///
/// Nested braces are tracked so that at-rules such as `@media` do not truncate
/// the block they wrap.
fn blocks(source: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut selector_start = 0usize;
    let mut body_start = 0usize;
    let mut depth = 0usize;

    for (index, byte) in source.bytes().enumerate() {
        match byte {
            b'{' => {
                if depth == 0 {
                    body_start = index + 1;
                }
                depth += 1;
            }
            b'}' => {
                if depth == 0 {
                    selector_start = index + 1;
                    continue;
                }

                depth -= 1;

                if depth == 0 {
                    let selector = source[selector_start..body_start.saturating_sub(1)].trim();
                    let body = &source[body_start..index];
                    out.push((selector.to_owned(), body.to_owned()));
                    selector_start = index + 1;
                }
            }
            _ => {}
        }
    }

    out
}

/// Splits a rule body into `(property, value)` pairs, lowercasing properties.
fn declarations(body: &str) -> Vec<(String, String)> {
    body.split(';')
        .filter_map(|entry| {
            let entry = entry.trim();
            let colon = entry.find(':')?;
            let property = entry[..colon].trim().to_ascii_lowercase();
            let value = entry[colon + 1..].trim();

            if property.is_empty() || value.is_empty() {
                return None;
            }

            Some((property, value.to_owned()))
        })
        .collect()
}

/// Returns the first family of a `font-family` value, without quotes.
fn parse_font_family(value: &str) -> Option<String> {
    let first = value.split(',').next()?.trim();
    let unquoted = first
        .strip_prefix('"')
        .and_then(|rest| rest.strip_suffix('"'))
        .or_else(|| {
            first
                .strip_prefix('\'')
                .and_then(|rest| rest.strip_suffix('\''))
        })
        .unwrap_or(first)
        .trim();

    if unquoted.is_empty() {
        None
    } else {
        Some(unquoted.to_owned())
    }
}

/// Returns the radius, in pixels, of the rule that styles a full `#pill`.
///
/// Half pills (`#pill-up`, `#pill-in`, ...) and leaves are ignored, as is any
/// rule that does not target a pill at all.
fn parse_pill_radius(source: &str, font_size_px: Option<f32>) -> Option<f32> {
    blocks(source)
        .into_iter()
        .filter(|(selector, _)| targets_full_pill(selector))
        .find_map(|(_, body)| {
            declarations(&body)
                .into_iter()
                .find(|(property, _)| property == "border-radius")
                .and_then(|(_, value)| {
                    let first = value.split_whitespace().next()?;
                    parse_length(first, font_size_px)
                })
        })
}

/// Reports whether a selector group targets the bare `#pill` identifier.
fn targets_full_pill(selector: &str) -> bool {
    let bytes = selector.as_bytes();
    let mut offset = 0usize;

    while let Some(found) = selector[offset..].find("#pill") {
        let start = offset + found;
        let end = start + "#pill".len();

        let boundary = match bytes.get(end) {
            None => true,
            Some(&next) => !(next.is_ascii_alphanumeric() || next == b'-' || next == b'_')
        };

        if boundary {
            return true;
        }

        offset = end;
    }

    false
}

/// Parses a CSS length into pixels.
///
/// `px`, `pt`, `em`, `rem` and unitless numbers are understood; anything else
/// yields [`None`]. `em` and `rem` fall back to a 16px root when the stylesheet
/// has no explicit font size.
fn parse_length(value: &str, font_size_px: Option<f32>) -> Option<f32> {
    let value = value.trim();
    let split = value
        .find(|c: char| !(c.is_ascii_digit() || c == '.' || c == '-' || c == '+'))
        .unwrap_or(value.len());

    let number: f32 = value[..split].parse().ok()?;
    let unit = value[split..].trim().to_ascii_lowercase();

    match unit.as_str() {
        "" | "px" => Some(number),
        "pt" => Some(number * PX_PER_PT),
        "em" | "rem" => Some(number * font_size_px.unwrap_or(DEFAULT_EM_PX)),
        _ => None
    }
}

/// Parses a CSS color in `rgb()`, `rgba()` or hexadecimal notation.
fn parse_color(value: &str) -> Option<Rgba> {
    let value = value.trim();

    if let Some(rest) = value.strip_prefix('#') {
        return parse_hex(rest);
    }

    let lowered = value.to_ascii_lowercase();
    let rest = lowered
        .strip_prefix("rgba")
        .or_else(|| lowered.strip_prefix("rgb"))?
        .trim_start();
    let inner = rest.strip_prefix('(')?;
    let inner = inner[..inner.find(')')?].to_owned();

    let parts: Vec<&str> = inner
        .split(|c: char| c == ',' || c == '/' || c.is_whitespace())
        .map(str::trim)
        .filter(|part| !part.is_empty())
        .collect();

    if parts.len() < 3 {
        return None;
    }

    let r = parse_channel(parts[0])?;
    let g = parse_channel(parts[1])?;
    let b = parse_channel(parts[2])?;
    let a = match parts.get(3) {
        Some(part) => parse_alpha(part)?,
        None => 1.0
    };

    Some(Rgba::rgba(r, g, b, a))
}

/// Parses one `rgb()` channel, accepting both absolute and percentage forms.
fn parse_channel(part: &str) -> Option<u8> {
    let value: f32 = match part.strip_suffix('%') {
        Some(number) => number.trim().parse::<f32>().ok()? * 2.55,
        None => part.parse::<f32>().ok()?
    };

    Some(value.round().clamp(0.0, 255.0) as u8)
}

/// Parses an alpha component, accepting both fractions and percentages.
fn parse_alpha(part: &str) -> Option<f32> {
    let value: f32 = match part.strip_suffix('%') {
        Some(number) => number.trim().parse::<f32>().ok()? / 100.0,
        None => part.parse::<f32>().ok()?
    };

    Some(value.clamp(0.0, 1.0))
}

/// Parses a hexadecimal color body (the part after `#`).
fn parse_hex(body: &str) -> Option<Rgba> {
    let body = body.trim();

    if !body.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }

    let expand = |c: u8| -> Option<u8> {
        let digit = (c as char).to_digit(16)? as u8;
        Some(digit * 17)
    };
    let pair = |slice: &str| -> Option<u8> { u8::from_str_radix(slice, 16).ok() };

    match body.len() {
        3 | 4 => {
            let bytes = body.as_bytes();
            let alpha = match bytes.get(3) {
                Some(&c) => f32::from(expand(c)?) / 255.0,
                None => 1.0
            };
            Some(Rgba::rgba(
                expand(bytes[0])?,
                expand(bytes[1])?,
                expand(bytes[2])?,
                alpha
            ))
        }
        6 | 8 => {
            let alpha = if body.len() == 8 {
                f32::from(pair(&body[6..8])?) / 255.0
            } else {
                1.0
            };
            Some(Rgba::rgba(
                pair(&body[0..2])?,
                pair(&body[2..4])?,
                pair(&body[4..6])?,
                alpha
            ))
        }
        _ => None
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use tempfile::TempDir;

    use super::*;

    const THEME_CSS: &str = r#"
/* generated by HyDE */
@define-color bar-bg rgba(27,29,28,0.01);
@define-color main-bg   rgba( 27 , 29 , 28 , 0.8 ) ;
@define-color main-fg #AAF0CD;
@define-color wb-act-bg rgb(195,172,118);
@define-color wb-act-fg rgba(255,240,204,1);
@define-color wb-hvr-bg #7d6c4b66;
@define-color wb-hvr-fg rgba(240,204,170,0.8);
@define-color unknown-key rgba(1,2,3,1);
@define-color broken-key not-a-color;
"#;

    const GLOBAL_CSS: &str = r#"
/*
 Dynamic Style Configuration
*/

* {
    border-radius: 0em;
    font-family: "JetBrainsMono Nerd Font","JetBrainsMono Nerd Font";
    font-size: 10px;
}
"#;

    const BORDER_RADIUS_CSS: &str = r#"
/* ? Leaf shape */
window#waybar.top #leaf,
window#waybar.top #leaf button {
    border-radius: 9pt 0 9pt 0;
}

/* ? half pill with the flat surface pointing upwards */
window#waybar.top #pill-up,
window#waybar.top #pill-up button {
    border-radius: 7pt 7pt 0 0;
}

window#waybar.top #pill-in tooltip {
    border-radius: 0 0 5pt 5pt;
}

/* ? Full Pill shape */
window#waybar.bottom #pill menuitem,
window#waybar.top #pill,
window#waybar.top #pill button {
    border-radius: 3pt 3pt 3pt 3pt;
}

tooltip {
    border-radius: 11pt;
}
"#;

    /// Writes the three HyDE stylesheets into a temporary configuration root.
    fn write_fixture(root: &Path) -> PathBuf {
        let waybar = root.join("waybar");
        let includes = waybar.join("includes");
        fs::create_dir_all(&includes).expect("create fixture directories");

        fs::write(waybar.join("theme.css"), THEME_CSS).expect("write theme.css");
        fs::write(includes.join("global.css"), GLOBAL_CSS).expect("write global.css");
        fs::write(includes.join("border-radius.css"), BORDER_RADIUS_CSS)
            .expect("write border-radius.css");

        waybar
    }

    fn assert_close(actual: f32, expected: f32) {
        assert!(
            (actual - expected).abs() < 1e-4,
            "expected {expected}, got {actual}"
        );
    }

    #[test]
    fn parses_rgba_with_alpha() {
        let color = parse_color("rgba(27,29,28,0.8)").expect("color");
        assert_eq!(color.r, 27);
        assert_eq!(color.g, 29);
        assert_eq!(color.b, 28);
        assert_close(color.a, 0.8);
    }

    #[test]
    fn parses_rgb_without_alpha() {
        assert_eq!(
            parse_color("rgb( 195 , 172 , 118 )"),
            Some(Rgba::rgb(195, 172, 118))
        );
    }

    #[test]
    fn parses_hex_colors() {
        assert_eq!(parse_color("#AAF0CD"), Some(Rgba::rgb(170, 240, 205)));
        assert_eq!(parse_color("#abc"), Some(Rgba::rgb(170, 187, 204)));

        let with_alpha = parse_color("#7d6c4b80").expect("color");
        assert_eq!((with_alpha.r, with_alpha.g, with_alpha.b), (125, 108, 75));
        assert_close(with_alpha.a, 128.0 / 255.0);
    }

    #[test]
    fn rejects_unparsable_colors() {
        assert_eq!(parse_color("not-a-color"), None);
        assert_eq!(parse_color("#12345"), None);
        assert_eq!(parse_color("rgba(1,2)"), None);
    }

    #[test]
    fn converts_points_to_pixels() {
        assert_close(parse_length("3pt", None).expect("length"), 4.0);
        assert_close(parse_length("9pt", None).expect("length"), 12.0);
        assert_close(parse_length("10px", None).expect("length"), 10.0);
        assert_close(parse_length("0em", Some(10.0)).expect("length"), 0.0);
        assert_close(parse_length("2em", Some(10.0)).expect("length"), 20.0);
        assert_eq!(parse_length("3vh", None), None);
    }

    #[test]
    fn picks_the_full_pill_radius() {
        let radius = parse_pill_radius(&strip_comments(BORDER_RADIUS_CSS), Some(10.0))
            .expect("pill radius");
        assert_close(radius, 4.0);
    }

    #[test]
    fn full_pill_selector_excludes_variants_and_leaves() {
        assert!(targets_full_pill("window#waybar.top #pill button"));
        assert!(targets_full_pill("window#waybar.top #pill,\n#pill menu"));
        assert!(!targets_full_pill("window#waybar.top #pill-up button"));
        assert!(!targets_full_pill("window#waybar.top #pill-in tooltip"));
        assert!(!targets_full_pill("window#waybar.top #pill-down"));
        assert!(!targets_full_pill("window#waybar.top #pill-left"));
        assert!(!targets_full_pill("window#waybar.top #pill-right"));
        assert!(!targets_full_pill("window#waybar.top #pill-out"));
        assert!(!targets_full_pill("window#waybar.top #leaf-inverse"));
        assert!(!targets_full_pill("tooltip"));
    }

    #[test]
    fn strips_comments() {
        assert_eq!(strip_comments("a/* x */b"), "a b");
        assert_eq!(strip_comments("a/* unterminated"), "a ");
    }

    #[test]
    fn loads_a_complete_theme() {
        let dir = TempDir::new().expect("tempdir");
        write_fixture(dir.path());

        let theme = load_from(dir.path());

        assert_eq!(theme.bar_background, Some(Rgba::rgba(27, 29, 28, 0.01)));
        assert_eq!(theme.module_background, Some(Rgba::rgba(27, 29, 28, 0.8)));
        assert_eq!(theme.text, Some(Rgba::rgb(170, 240, 205)));
        assert_eq!(theme.active_background, Some(Rgba::rgb(195, 172, 118)));
        assert_eq!(theme.active_text, Some(Rgba::rgb(255, 240, 204)));
        assert_eq!(theme.hover_text, Some(Rgba::rgba(240, 204, 170, 0.8)));

        let hover_background = theme.hover_background.expect("hover background");
        assert_eq!(
            (hover_background.r, hover_background.g, hover_background.b),
            (125, 108, 75)
        );
        assert_close(hover_background.a, 102.0 / 255.0);

        assert_eq!(
            theme.font_family.as_deref(),
            Some("JetBrainsMono Nerd Font")
        );
        assert_close(theme.font_size_px.expect("font size"), 10.0);
        assert_close(theme.radius_px.expect("radius"), 4.0);
    }

    #[test]
    fn missing_directory_yields_an_empty_theme() {
        let dir = TempDir::new().expect("tempdir");
        let missing = dir.path().join("does-not-exist");

        assert_eq!(load_from(&missing), HydeTheme::default());
    }

    #[test]
    fn partial_sources_leave_other_fields_unset() {
        let dir = TempDir::new().expect("tempdir");
        let waybar = dir.path().join("waybar");
        fs::create_dir_all(&waybar).expect("create waybar directory");
        fs::write(waybar.join("theme.css"), "@define-color main-fg #ffffff;")
            .expect("write theme.css");

        let theme = load_from(dir.path());

        assert_eq!(theme.text, Some(Rgba::rgb(255, 255, 255)));
        assert_eq!(theme.font_family, None);
        assert_eq!(theme.font_size_px, None);
        assert_eq!(theme.radius_px, None);
        assert_eq!(theme.bar_background, None);
    }
}
