//! Built in glyph catalogue: every icon the bar knows and its default glyph.

#[derive(Copy, Clone, Default, Debug, PartialEq, Eq, Hash)]
pub enum Icons {
    #[default]
    None,
    AppLauncher,
    Clipboard,
    Refresh,
    Trash,
    Download,
    ViewGrid,
    ViewList,
    NoUpdatesAvailable,
    UpdatesAvailable,
    MenuClosed,
    MenuOpen,
    Record,
    Stop,
    WindowCapture,
    Cpu,
    Gpu,
    IntegratedGpu,
    Accelerator,
    Mem,
    Temp,
    Speaker0,
    Speaker1,
    Speaker2,
    Speaker3,
    Headphones0,
    Headphones1,
    Headset,
    Mic0,
    Mic1,
    MonitorSpeaker,
    ScreenShare,
    Battery0,
    Battery1,
    Battery2,
    Battery3,
    Battery4,
    BatteryCharging,
    Wifi0,
    Wifi1,
    Wifi2,
    Wifi3,
    Wifi4,
    Wifi5,
    WifiLock1,
    WifiLock2,
    WifiLock3,
    WifiLock4,
    WifiLock5,
    Ethernet,
    Vpn,
    Bluetooth,
    PowerSaver,
    Balanced,
    Performance,
    EyeOpened,
    EyeClosed,
    Lock,
    Power,
    Reboot,
    Suspend,
    Logout,
    LeftArrow,
    RightArrow,
    LeftChevron,
    RightChevron,
    Brightness,
    Point,
    AreaSelect,
    Bell,
    Camera,
    Close,
    Fullscreen,
    Airplane,
    Webcam,
    SkipPrevious,
    Play,
    Pause,
    SkipNext,
    MusicNote,
    Drive,
    IpAddress,
    DownloadSpeed,
    UploadSpeed,
    Copy,
    IdleInhibitorActive,
    IdleInhibitorInactive,
    Settings,
    Themes,
    Wallpaper,
    BarLayout,
    KeybindHint,
    NightLight,
    GameMode,
    Weather,
    /// Marks work signed by the person at the keyboard.
    Authored
}

impl Icons {
    /// Every icon that can be overridden from the configuration.
    pub const ALL: [Self; 96] = [
        Self::None,
        Self::AppLauncher,
        Self::Clipboard,
        Self::Refresh,
        Self::Trash,
        Self::Download,
        Self::ViewGrid,
        Self::ViewList,
        Self::NoUpdatesAvailable,
        Self::UpdatesAvailable,
        Self::MenuClosed,
        Self::MenuOpen,
        Self::Record,
        Self::Stop,
        Self::WindowCapture,
        Self::Cpu,
        Self::Gpu,
        Self::IntegratedGpu,
        Self::Accelerator,
        Self::Mem,
        Self::Temp,
        Self::Speaker0,
        Self::Speaker1,
        Self::Speaker2,
        Self::Speaker3,
        Self::Headphones0,
        Self::Headphones1,
        Self::Headset,
        Self::Mic0,
        Self::Mic1,
        Self::MonitorSpeaker,
        Self::ScreenShare,
        Self::Battery0,
        Self::Battery1,
        Self::Battery2,
        Self::Battery3,
        Self::Battery4,
        Self::BatteryCharging,
        Self::Wifi0,
        Self::Wifi1,
        Self::Wifi2,
        Self::Wifi3,
        Self::Wifi4,
        Self::Wifi5,
        Self::WifiLock1,
        Self::WifiLock2,
        Self::WifiLock3,
        Self::WifiLock4,
        Self::WifiLock5,
        Self::Ethernet,
        Self::Vpn,
        Self::Bluetooth,
        Self::PowerSaver,
        Self::Balanced,
        Self::Performance,
        Self::EyeOpened,
        Self::EyeClosed,
        Self::Lock,
        Self::Power,
        Self::Reboot,
        Self::Suspend,
        Self::Logout,
        Self::LeftArrow,
        Self::RightArrow,
        Self::LeftChevron,
        Self::RightChevron,
        Self::Brightness,
        Self::Point,
        Self::AreaSelect,
        Self::Bell,
        Self::Camera,
        Self::Close,
        Self::Fullscreen,
        Self::Airplane,
        Self::Webcam,
        Self::SkipPrevious,
        Self::Play,
        Self::Pause,
        Self::SkipNext,
        Self::MusicNote,
        Self::Drive,
        Self::IpAddress,
        Self::DownloadSpeed,
        Self::UploadSpeed,
        Self::Copy,
        Self::IdleInhibitorActive,
        Self::IdleInhibitorInactive,
        Self::Settings,
        Self::Themes,
        Self::Wallpaper,
        Self::BarLayout,
        Self::KeybindHint,
        Self::NightLight,
        Self::GameMode,
        Self::Weather,
        Self::Authored
    ];

    /// Key used to address the icon inside the `[icons]` configuration table.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::AppLauncher => "app_launcher",
            Self::Clipboard => "clipboard",
            Self::Refresh => "refresh",
            Self::Trash => "trash",
            Self::Download => "download",
            Self::ViewGrid => "view_grid",
            Self::ViewList => "view_list",
            Self::NoUpdatesAvailable => "no_updates_available",
            Self::UpdatesAvailable => "updates_available",
            Self::MenuClosed => "menu_closed",
            Self::MenuOpen => "menu_open",
            Self::Cpu => "cpu",
            Self::Gpu => "gpu",
            Self::IntegratedGpu => "integrated_gpu",
            Self::Accelerator => "accelerator",
            Self::Mem => "mem",
            Self::Temp => "temp",
            Self::Speaker0 => "speaker0",
            Self::Speaker1 => "speaker1",
            Self::Speaker2 => "speaker2",
            Self::Speaker3 => "speaker3",
            Self::Headphones0 => "headphones0",
            Self::Headphones1 => "headphones1",
            Self::Headset => "headset",
            Self::Mic0 => "mic0",
            Self::Mic1 => "mic1",
            Self::MonitorSpeaker => "monitor_speaker",
            Self::ScreenShare => "screen_share",
            Self::Battery0 => "battery0",
            Self::Battery1 => "battery1",
            Self::Battery2 => "battery2",
            Self::Battery3 => "battery3",
            Self::Battery4 => "battery4",
            Self::BatteryCharging => "battery_charging",
            Self::Wifi0 => "wifi0",
            Self::Wifi1 => "wifi1",
            Self::Wifi2 => "wifi2",
            Self::Wifi3 => "wifi3",
            Self::Wifi4 => "wifi4",
            Self::Wifi5 => "wifi5",
            Self::WifiLock1 => "wifi_lock1",
            Self::WifiLock2 => "wifi_lock2",
            Self::WifiLock3 => "wifi_lock3",
            Self::WifiLock4 => "wifi_lock4",
            Self::WifiLock5 => "wifi_lock5",
            Self::Ethernet => "ethernet",
            Self::Vpn => "vpn",
            Self::Bluetooth => "bluetooth",
            Self::PowerSaver => "power_saver",
            Self::Balanced => "balanced",
            Self::Performance => "performance",
            Self::EyeOpened => "eye_opened",
            Self::EyeClosed => "eye_closed",
            Self::Lock => "lock",
            Self::Power => "power",
            Self::Reboot => "reboot",
            Self::Suspend => "suspend",
            Self::Logout => "logout",
            Self::LeftArrow => "left_arrow",
            Self::RightArrow => "right_arrow",
            Self::LeftChevron => "left_chevron",
            Self::RightChevron => "right_chevron",
            Self::Brightness => "brightness",
            Self::Point => "point",
            Self::AreaSelect => "area_select",
            Self::Bell => "bell",
            Self::Camera => "camera",
            Self::Fullscreen => "fullscreen",
            Self::Record => "record",
            Self::Stop => "stop",
            Self::WindowCapture => "window_capture",
            Self::Close => "close",
            Self::Airplane => "airplane",
            Self::Webcam => "webcam",
            Self::SkipPrevious => "skip_previous",
            Self::Play => "play",
            Self::Pause => "pause",
            Self::SkipNext => "skip_next",
            Self::MusicNote => "music_note",
            Self::Drive => "drive",
            Self::IpAddress => "ip_address",
            Self::DownloadSpeed => "download_speed",
            Self::UploadSpeed => "upload_speed",
            Self::Copy => "copy",
            Self::IdleInhibitorActive => "idle_inhibitor_active",
            Self::IdleInhibitorInactive => "idle_inhibitor_inactive",
            Self::Settings => "settings",
            Self::Themes => "themes",
            Self::Wallpaper => "wallpaper",
            Self::BarLayout => "bar_layout",
            Self::KeybindHint => "keybind_hint",
            Self::NightLight => "night_light",
            Self::GameMode => "game_mode",
            Self::Weather => "weather",
            Self::Authored => "authored"
        }
    }

    /// Resolves a configuration key back to the icon it addresses.
    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|icon| icon.name() == name)
    }

    /// Glyph compiled into the binary, used when no override applies.
    #[must_use]
    #[expect(
        clippy::match_same_arms,
        reason = "each icon names its own glyph even when glyphs coincide"
    )]
    pub const fn default_glyph(self) -> &'static str {
        match self {
            Self::None => "",
            Self::AppLauncher => "󱗼",
            Self::Clipboard => "󰅌",
            Self::Refresh => "󰑐",
            Self::Trash => "󰆴",
            Self::Download => "󰇚",
            Self::ViewGrid => "󰕰",
            Self::ViewList => "󰕳",
            Self::NoUpdatesAvailable => "󰗠",
            Self::UpdatesAvailable => "󰳛",
            Self::MenuClosed => "",
            Self::MenuOpen => "",
            Self::Cpu => "󰔂",
            Self::Gpu => "󰢮",
            Self::IntegratedGpu => "󰘚",
            Self::Accelerator => "󰧑",
            Self::Mem => "",
            Self::Temp => "󰔏",
            Self::Speaker0 => "󰸈",
            Self::Speaker1 => "󰕿",
            Self::Speaker2 => "󰖀",
            Self::Speaker3 => "󰕾",
            Self::Headphones0 => "󰟎",
            Self::Headphones1 => "󰋋",
            Self::Headset => "󰋎",
            Self::Mic0 => "󰍭",
            Self::Mic1 => "󰍬",
            Self::ScreenShare => "󱒃",
            Self::MonitorSpeaker => "󰽟",
            Self::Battery0 => "󰂃",
            Self::Battery1 => "󰁼",
            Self::Battery2 => "󰁾",
            Self::Battery3 => "󰂀",
            Self::Battery4 => "󰁹",
            Self::BatteryCharging => "󰂄",
            Self::Wifi0 => "󰤭",
            Self::Wifi1 => "󰤯",
            Self::Wifi2 => "󰤟",
            Self::Wifi3 => "󰤢",
            Self::Wifi4 => "󰤥",
            Self::Wifi5 => "󰤨",
            Self::WifiLock1 => "󰤬",
            Self::WifiLock2 => "󰤡",
            Self::WifiLock3 => "󰤤",
            Self::WifiLock4 => "󰤧",
            Self::WifiLock5 => "󰤪",
            Self::Ethernet => "󰈀",
            Self::Vpn => "󰖂",
            Self::Bluetooth => "󰂯",
            Self::PowerSaver => "󰾆",
            Self::Balanced => "󰾅",
            Self::Performance => "󰓅",
            Self::EyeOpened => "󰈈",
            Self::EyeClosed => "󰈉",
            Self::Lock => "󰌾",
            Self::Power => "󰐥",
            Self::Reboot => "󰑐",
            Self::Suspend => "󰤄",
            Self::Logout => "󰗽",
            Self::LeftArrow => "󰁍",
            Self::RightArrow => "󰁔",
            Self::LeftChevron => "󰅁",
            Self::RightChevron => "󰅂",
            Self::Brightness => "󰃠",
            Self::Point => "",
            Self::AreaSelect => "\u{f0a6c}",
            Self::Bell => "\u{f009a}",
            Self::Camera => "\u{f0100}",
            Self::Fullscreen => "\u{f0293}",
            Self::Record => "\u{f044a}",
            Self::Stop => "\u{f04db}",
            Self::WindowCapture => "\u{f05af}",
            Self::Close => "󰅖",
            Self::Airplane => "󰀝",
            Self::Webcam => "",
            Self::SkipPrevious => "󰒮",
            Self::Play => "󰐊",
            Self::Pause => "󰏤",
            Self::SkipNext => "󰒭",
            Self::MusicNote => "󰎇",
            Self::Drive => "󰋊",
            Self::IpAddress => "󰩠",
            Self::DownloadSpeed => "󰛴",
            Self::UploadSpeed => "󰛶",
            Self::Copy => "󰆏",
            Self::IdleInhibitorActive => "\u{f0176}",
            Self::IdleInhibitorInactive => "\u{f06ca}",
            Self::Settings => "\u{f0493}",
            Self::Themes => "\u{f00e1}",
            Self::Wallpaper => "\u{f0b7c}",
            Self::BarLayout => "\u{f1985}",
            Self::KeybindHint => "\u{f030c}",
            Self::NightLight => "\u{f0748}",
            Self::GameMode => "\u{f0eb5}",
            Self::Weather => "\u{f0590}",
            Self::Authored => "\u{f04ce}"
        }
    }
}

impl From<Icons> for &'static str {
    fn from(icon: Icons) -> &'static str {
        icon.default_glyph()
    }
}
